# ---- Build stage ----
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci && npm cache clean --force

COPY . .

ARG VITE_BASE_API_URL
ENV VITE_BASE_API_URL=$VITE_BASE_API_URL

RUN npm run build -- --mode uat

# ---- Runtime stage (serve with nginx) ----
FROM nginx:alpine


COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


# docker build -f docker/Dockerfile.uat \
#   --build-arg VITE_BASE_API_URL=/api \
#   -t teim123/krisna_air:frontend-uat-1.0.0 .


# docker push teim123/krisna_air:frontend-uat-1.0.0