# Use node base image
FROM node:22-alpine AS builder

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependancies
RUN npm ci && npm cache clean --force

# Copy the source code
COPY . .

ARG VITE_BASE_API_URL
ENV VITE_BASE_API_URL=$VITE_BASE_API_URL
 
RUN node -e "console.log('VITE_BASE_API_URL=', process.env.VITE_BASE_API_URL)"
# Build the application
RUN npm run build -- --mode uat


# Use nginx as the base image for serving the application
FROM nginx:alpine

# Copy the built application from the builder stage to the nginx html directory
COPY --from=builder /app/dist /usr/share/nginx/html

# Expose port 80 to the outside world
EXPOSE 80

# Start nginx when the container launches
CMD ["nginx", "-g", "daemon off;"]