# Use node slim as the base image
FROM node:22.21.1-slim AS builder

# Set the working directory 
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependancies 
RUN npm install

# Copy the source code 
COPY . . 

