# Use node slim as the base image
FROM node:22-alpine AS builder

# Set the working directory 
WORKDIR /app

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependancies 
RUN npm ci && npm cache clean --force

# Copy the source code 
COPY . . 

